In [2]:
import numpy as np
import torch
from torch.utils import data

In [3]:
def synthetic_data(w, b, num_examples):
  X = torch.normal(0, 1, size = (num_examples, len(w)))
  y = torch.matmul(X, w.reshape(len(w), 1)) + b
  y += torch.normal(0, 0.01, y.shape)
  return X, y.reshape(num_examples, 1)


In [4]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
X_in, y_labels = synthetic_data(true_w, true_b, 1000)

In [8]:
def load_array(data_arrays, batch_size, is_Train=True):
  dataset = data.TensorDataset(*data_arrays)
  return data.DataLoader(dataset, batch_size=batch_size, shuffle=is_Train)

batch_size = 10
data_iter = load_array((X_in, y_labels), batch_size)

In [11]:
iter(data_iter)

In [12]:
from torch import nn

In [14]:
net = nn.Sequential(nn.Linear(2, 1))

In [15]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [37]:
loss = nn.MSELoss(reduction='sum')
trainer = torch.optim.SGD(net.parameters(), lr = 0.03)

In [38]:
num_epochs = 3
for epoch in range(num_epochs):
  for X, y in data_iter:
    l = loss(net(X), y)
    trainer.zero_grad()
    l.backward()
    trainer.step()
  l = loss(net(X_in), y_labels)
  print(f'epoch: {epoch+1}, loss: {l:.5f}')

epoch: 1, loss: 0.10759
epoch: 2, loss: 0.10220
epoch: 3, loss: 0.11840


In [39]:
net[0].weight.data

tensor([[ 2.0008, -3.4040]])

In [40]:
net[0].bias.data

tensor([4.2000])