<a href="https://colab.research.google.com/github/hmh10098/d2l/blob/main/5_4_CustomLayers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
from torch import nn
from torch.nn import functional as F

class CenteredLayer(nn.Module):
  def __init__(self):
    super().__init__()
  def forward(self, X):
    return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.Tensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [6]:
Y = net(torch.rand(4, 8))
print(Y.shape)
print(Y.mean())

torch.Size([4, 128])
tensor(5.5879e-09, grad_fn=<MeanBackward0>)


In [25]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.zeros(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [26]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.4993, -1.0852, -0.8445],
        [-0.4952,  0.2940, -1.1424],
        [ 0.8322, -1.0493, -2.1068],
        [-0.4934,  2.5633,  0.0462],
        [-0.9246,  0.6271, -1.0315]], requires_grad=True)

In [27]:
linear.bias

Parameter containing:
tensor([0., 0., 0.], requires_grad=True)

In [31]:
linear(torch.rand(2, 5))


tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 1.6511, 0.0000]])

In [32]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.9881],
        [1.0578]])